name: ff_tournament
description: Free Fire Max Tournament App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
